[package]
name = "respaldo_diario_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-s3 = "1.16.0"
aws-config = "1.1.6"
tokio = { version = "1.36.0", features = ["full"] }
